### ISSUE TITLE
Creating xarray friendly zarr file of geospatial data

### ISSUE THREAD

**Issue by Marston** [zarr-developers/geozarr-spec#9]
I would like to read a grib file and create from the records a 5D tensor array: `('time', 'name', 'lev', 'lat', 'lon')`. I can create this easily in `zarr` by creating a dataset and load it by looping over the dimension, `name`. This creates a nice `zarr` but `xarray` cannot read it because of some missing dimension issues. I have all the metadata, I just need an example of how to write georeferenced data to `zarr`.
There doesn't seem to be any docs or code in this repo. Can someone point me in the right direction?

**Comment by briannapagan** [comment]
Hi @Marston this might be useful: https://nbviewer.org/gist/rsignell-usgs/a047178ee12d44c2a7900ee86ba2fbc7
Going to CC: @lsterzinger and @rsignell-usgs

**Comment by lsterzinger** [comment]
Hi @Marston, Kerchunk would be a good option I think for your usecase (this is what @briannapagan linked, though it was  called `fsspec_reference_maker` at the time). Some of the API has changed since, especially concerning `kerchunk.combine.MultiZarrToZarr`: https://fsspec.github.io/kerchunk/tutorial.html#combine-multiple-kerchunked-datasets-into-a-single-logical-aggregate-dataset

**Comment by rsignell-usgs** [comment]
@Marston  did you have success?

**Comment by Marston** [comment]
@rsignell-usgs  I have was successful but not using kerchunk. I work in an agile environment and the ticket I had was completed. Nevertheless, I've flagged kerchunk as something to research.
